version: "3.8"
services:
  store:
    build: ./store
    ports:
      - "9000:9000"

  api:
    build: ./api
    depends_on:
      - store
    ports:
      - "8000:8000"

  queue:
    build: ./queue
    # not yet used in the MVP
